# Generated by Django 3.2.13 on 2022-10-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221022_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Number of recalls'),
        ),
    ]
